# Generated by Django 4.0.5 on 2022-10-14 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('urlimga', models.CharField(max_length=200)),
                ('office', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('urlimg', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.about')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('urlimg', models.CharField(max_length=200)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.about')),
            ],
        ),
    ]
